// scripts/vendor-fonts.js
// Download the latin-subset woff2 files for the app's fonts (Barlow, Barlow
// Condensed, JetBrains Mono) from Google Fonts and generate a self-contained
// public/vendor/fonts/fonts.css with local @font-face rules.
//
// Purpose: the packaged Electron app must render offline (CLAUDE.md packaging
// rule). Previously the fonts loaded from fonts.googleapis.com/fonts.gstatic.com
// at runtime; this vendors them into the asar via public/**/*.
//
// Usage: node scripts/vendor-fonts.js
// Re-run any time the font set or weights in index.html change.

const fs = require('fs');
const path = require('path');
const https = require('https');

const FONTS_URL = 'https://fonts.googleapis.com/css2?family=Barlow:wght@400;500;600;700&family=Barlow+Condensed:wght@500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';
const OUT_DIR = path.join(__dirname, '..', 'public', 'vendor', 'fonts');

function get(url) {
  return new Promise((resolve, reject) => {
    const req = https.get(url, { headers: { 'User-Agent': UA } }, (res) => {
      if (res.statusCode >= 400) {
        reject(new Error(`HTTP ${res.statusCode} for ${url}`));
        res.resume();
        return;
      }
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
    });
    req.on('error', reject);
  });
}

function slug(family) {
  return family.toLowerCase().replace(/[^a-z0-9]+/g, '-');
}

async function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const css = (await get(FONTS_URL)).toString('utf8');

  // Pair each @font-face block with the /* latin */ comment that precedes it.
  const comments = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\//g)]
    .map((m) => ({ subset: m[1], idx: m.index }));
  const blocks = [...css.matchAll(/@font-face\s*\{([^{}]*)\}/g)]
    .map((m) => ({ body: m[1], idx: m.index }));

  const latin = blocks.filter((b) => {
    const prev = comments.filter((c) => c.idx < b.idx).pop();
    return prev && prev.subset === 'latin';
  });

  if (latin.length === 0) {
    throw new Error('No latin subset @font-face blocks found in Google Fonts CSS');
  }

  const outRules = [];
  const seen = new Set();

  for (const { body } of latin) {
    const family = /font-family:\s*'([^']+)'/.exec(body)[1];
    const weight = /font-weight:\s*(\d+)/.exec(body)[1];
    const style = /font-style:\s*(\w+)/.exec(body)[1] || 'normal';
    const display = /font-display:\s*(\w+)/.exec(body)[1] || 'swap';
    const unicodeRange = /unicode-range:\s*([^;]+)/.exec(body);
    const srcUrl = /url\((https:[^)]+)\)/.exec(body)[1];

    const fname = `${slug(family)}-${weight}${style === 'italic' ? '-italic' : ''}.woff2`;
    // woff2 files live in the same directory as fonts.css, so the url() is
    // relative to fonts.css itself (no subdir prefix).
    const local = fname;

    const buf = await get(srcUrl);
    if (buf.length === 0) {
      throw new Error(`Empty download for ${srcUrl}`);
    }
    fs.writeFileSync(path.join(OUT_DIR, fname), buf);

    let rule = `@font-face {\n  font-family: '${family}';\n  font-style: ${style};\n  font-weight: ${weight};\n  font-display: ${display};\n  src: url(${local}) format('woff2');`;
    if (unicodeRange) rule += `\n  unicode-range: ${unicodeRange[1]};`;
    rule += '\n}\n';
    outRules.push(rule);
    seen.add(fname);
  }

  const header = `/* Generated by scripts/vendor-fonts.js — do not edit by hand. */\n`;
  fs.writeFileSync(path.join(OUT_DIR, 'fonts.css'), header + outRules.join('\n'));

  console.log(`Vendored ${seen.size} latin woff2 files -> public/vendor/fonts/`);
  console.log(`Wrote public/vendor/fonts/fonts.css (${latin.length} @font-face rules)`);
}

main().catch((err) => {
  console.error('vendor-fonts failed:', err.message);
  process.exit(1);
});
